/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShellRouteImport } from './routes/_shell'
import { Route as AboutRouteImport } from './routes/about'
import { Route as ShellDashboardRouteImport } from './routes/_shell.dashboard'
import { Route as ShellDocumentationRouteImport } from './routes/_shell.documentation'
import { Route as ShellModule1RouteImport } from './routes/_shell.module-1'
import { Route as ShellModule2RouteImport } from './routes/_shell.module-2'
import { Route as ShellModule3RouteImport } from './routes/_shell.module-3'
import { Route as ShellModule4RouteImport } from './routes/_shell.module-4'
import { Route as ShellModule5RouteImport } from './routes/_shell.module-5'
import { Route as ShellSettingsRouteImport } from './routes/_shell.settings'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellRoute = ShellRouteImport.update({
  id: '/_shell',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const ShellDashboardRoute = ShellDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ShellRoute,
} as any)
const ShellDocumentationRoute = ShellDocumentationRouteImport.update({
  id: '/documentation',
  path: '/documentation',
  getParentRoute: () => ShellRoute,
} as any)
const ShellModule1Route = ShellModule1RouteImport.update({
  id: '/module-1',
  path: '/module-1',
  getParentRoute: () => ShellRoute,
} as any)
const ShellModule2Route = ShellModule2RouteImport.update({
  id: '/module-2',
  path: '/module-2',
  getParentRoute: () => ShellRoute,
} as any)
const ShellModule3Route = ShellModule3RouteImport.update({
  id: '/module-3',
  path: '/module-3',
  getParentRoute: () => ShellRoute,
} as any)
const ShellModule4Route = ShellModule4RouteImport.update({
  id: '/module-4',
  path: '/module-4',
  getParentRoute: () => ShellRoute,
} as any)
const ShellModule5Route = ShellModule5RouteImport.update({
  id: '/module-5',
  path: '/module-5',
  getParentRoute: () => ShellRoute,
} as any)
const ShellSettingsRoute = ShellSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => ShellRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof ShellDashboardRoute
  '/documentation': typeof ShellDocumentationRoute
  '/module-1': typeof ShellModule1Route
  '/module-2': typeof ShellModule2Route
  '/module-3': typeof ShellModule3Route
  '/module-4': typeof ShellModule4Route
  '/module-5': typeof ShellModule5Route
  '/settings': typeof ShellSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/dashboard': typeof ShellDashboardRoute
  '/documentation': typeof ShellDocumentationRoute
  '/module-1': typeof ShellModule1Route
  '/module-2': typeof ShellModule2Route
  '/module-3': typeof ShellModule3Route
  '/module-4': typeof ShellModule4Route
  '/module-5': typeof ShellModule5Route
  '/settings': typeof ShellSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_shell': typeof ShellRouteWithChildren
  '/about': typeof AboutRoute
  '/_shell/dashboard': typeof ShellDashboardRoute
  '/_shell/documentation': typeof ShellDocumentationRoute
  '/_shell/module-1': typeof ShellModule1Route
  '/_shell/module-2': typeof ShellModule2Route
  '/_shell/module-3': typeof ShellModule3Route
  '/_shell/module-4': typeof ShellModule4Route
  '/_shell/module-5': typeof ShellModule5Route
  '/_shell/settings': typeof ShellSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/dashboard'
    | '/documentation'
    | '/module-1'
    | '/module-2'
    | '/module-3'
    | '/module-4'
    | '/module-5'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/dashboard'
    | '/documentation'
    | '/module-1'
    | '/module-2'
    | '/module-3'
    | '/module-4'
    | '/module-5'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_shell'
    | '/about'
    | '/_shell/dashboard'
    | '/_shell/documentation'
    | '/_shell/module-1'
    | '/_shell/module-2'
    | '/_shell/module-3'
    | '/_shell/module-4'
    | '/_shell/module-5'
    | '/_shell/settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ShellRoute: typeof ShellRouteWithChildren
  AboutRoute: typeof AboutRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell': {
      id: '/_shell'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof ShellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_shell/dashboard': {
      id: '/_shell/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ShellDashboardRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/documentation': {
      id: '/_shell/documentation'
      path: '/documentation'
      fullPath: '/documentation'
      preLoaderRoute: typeof ShellDocumentationRouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/module-1': {
      id: '/_shell/module-1'
      path: '/module-1'
      fullPath: '/module-1'
      preLoaderRoute: typeof ShellModule1RouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/module-2': {
      id: '/_shell/module-2'
      path: '/module-2'
      fullPath: '/module-2'
      preLoaderRoute: typeof ShellModule2RouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/module-3': {
      id: '/_shell/module-3'
      path: '/module-3'
      fullPath: '/module-3'
      preLoaderRoute: typeof ShellModule3RouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/module-4': {
      id: '/_shell/module-4'
      path: '/module-4'
      fullPath: '/module-4'
      preLoaderRoute: typeof ShellModule4RouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/module-5': {
      id: '/_shell/module-5'
      path: '/module-5'
      fullPath: '/module-5'
      preLoaderRoute: typeof ShellModule5RouteImport
      parentRoute: typeof ShellRoute
    }
    '/_shell/settings': {
      id: '/_shell/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ShellSettingsRouteImport
      parentRoute: typeof ShellRoute
    }
  }
}

interface ShellRouteChildren {
  ShellDashboardRoute: typeof ShellDashboardRoute
  ShellDocumentationRoute: typeof ShellDocumentationRoute
  ShellModule1Route: typeof ShellModule1Route
  ShellModule2Route: typeof ShellModule2Route
  ShellModule3Route: typeof ShellModule3Route
  ShellModule4Route: typeof ShellModule4Route
  ShellModule5Route: typeof ShellModule5Route
  ShellSettingsRoute: typeof ShellSettingsRoute
}

const ShellRouteChildren: ShellRouteChildren = {
  ShellDashboardRoute: ShellDashboardRoute,
  ShellDocumentationRoute: ShellDocumentationRoute,
  ShellModule1Route: ShellModule1Route,
  ShellModule2Route: ShellModule2Route,
  ShellModule3Route: ShellModule3Route,
  ShellModule4Route: ShellModule4Route,
  ShellModule5Route: ShellModule5Route,
  ShellSettingsRoute: ShellSettingsRoute,
}

const ShellRouteWithChildren = ShellRoute._addFileChildren(ShellRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ShellRoute: ShellRouteWithChildren,
  AboutRoute: AboutRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
